name: 'Add label to issue'
description: 'Finds a label in the issue title and adds it'
inputs:
  repo-token:
    description: 'The github authentication token'
    required: true
outputs:
  time: # id of output
    description: 'The time the action was executed'
runs:
  using: 'node16'
  main: 'index.js'