name: 'Add label to issue'
description: 'Finds a label in the issue title and adds it to the issue'
inputs:
  issue-id:
    description: 'The issue that will be labeled'
    default: ${{github.event.issue.node_id}}
  issue-title:
    description: 'The issue title string'
    default: ${{github.event.issue.title}}
  column-name:
    description: 'The project column in which the issue should be added'
    default: 'To do'
  parse-labels:
    description: 'Determines if the action should parse the title for labels'
    default: true
  parse-project:
    description: 'Determines if the action should parse the title for a project'
    default: true
  parse-assignees:
    description: 'Determines if the action should parse the title for assignees'
    default: true
  auto-parse-project:
    description: 'Determines if the action should parse the title for a project'
    default: false
  auto-parse-project-names:
    description: 'Comma-separated tokens used for automatic project parsing'
    default: 'code, report'
  repo-token:
    description: 'A github authentication token'
    default: ${{github.token}}
outputs:
  labels-added:
    description: 'The labels that were added to the issue'
  project-name:
    description: 'The project to which the issue was added'
runs:
  using: 'node16'
  main: 'index.js'